const BlogData = [
    {
        id: 1,
        date: "January 01, 2020",
        category: "Design",
        title: "Modern Design Concept",
        cover: "/images/singlepage/blog-1.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 2,
        date: "January 15, 2020",
        category: "Traveling",
        title: "An Extended Vacation",
        cover: "/images/singlepage/blog-2.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 3,
        date: "January 31, 2020",
        category: "Business",
        title: "My Home Design Plan",
        cover: "/images/singlepage/blog-3.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 4,
        date: "February 02, 2020",
        category: "Content Writing",
        title: "Smart and Flexible Plan",
        cover: "/images/singlepage/blog-4.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 5,
        date: "April 01, 2020",
        category: "Business",
        title: "Investment Planning",
        cover: "/images/singlepage/blog-5.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 6,
        date: "June 01, 2020",
        category: "Travel",
        title: "Book a Flight Anwhere",
        cover: "/images/singlepage/blog-6.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 7,
        date: "January 30, 2022",
        category: "Business",
        title: "The Most Advance Business Plan",
        cover: "/images/singlepage/blog-5.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 8,
        date: "February 01, 2022",
        category: "Content Writing",
        title: "The Most Advance Business Plan",
        cover: "/images/singlepage/blog-3.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
    {
        id: 9,
        date: "February 16, 2022",
        category: "Content Writing",
        title: "The Most Advance Business Plan",
        cover: "/images/singlepage/blog-2.jpg",
        para: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem sed deleniti ipsam porro fuga iusto soluta quibusdam commodi quis hic",
    },
]

export default BlogData